// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.myNetty.proto;

public interface StudentResquestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.myNetty.proto.StudentResquest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
